name: Deploy to Firebase Hosting
on:
  workflow_dispatch:    # ‚Üê ADD THIS
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.firebaseServiceAccount }}
          firebaseServiceAccount: ${{ secrets.firebaseServiceAccount }}
          channelId: live
          projectId: instagram-test-a9a21
          entryPoint: "."
